### ISSUE TITLE
Don't use Immutable

### ISSUE THREAD

**Issue by bendrucker** [chinedufn/solid-state#5]
Huge byte and perf cost for no reason here. Immutable is hugely powerful for complex cases, but not necessary here. With what you're actually doing, immutable's equality mechanism isn't helping you at all. You can just as easily check for `oldValue === newValue`. You're basically just using immutable to clone objects which could be done faster and with fewer bytes. 

Immutable is useful when you are passing around objects and you expect downstream code to consume and manipulate them. You want to make it easy to transform the data, but hard to accidentally mutate parent state.

Here you know exactly how the data can be mutated (via `set`) and accessed (a fn call as suggested in #4). You can just shallow or deep copy as needed there.

Pretty sure you should just be using https://github.com/nrw/observ-varhash though

**Comment by chinedufn** [comment]
> immutable's equality mechanism isn't helping you at all

Will think about this

> Pretty sure you should just be using observ-varhash

Thankfully this is a small enough (SLOC wise) piece of my application that I can afford the fun of managing it myself ;)

**Comment by chinedufn** [comment]
Removing immutable for now. Might revisit this in the future. - b4805ccbadeb363e6fc0fe0436492b14ba61dd3d

Thank you!
