### ISSUE TITLE
Dehypeify description

### ISSUE THREAD

**Issue by bendrucker** [chinedufn/solid-state#6]
> Confidently maintain state and react to changes

Confidently implies that you can't be confident in some other way of doing things but you never explain what the old way is

> Maintain

If by maintain you're referencing immutability, just say that

**Comment by chinedufn** [comment]
'Confidently maintain an agile unicorn state while innovative and secure listener functions deliver happiness to users' - b4805ccbadeb363e6fc0fe0436492b14ba61dd3d

Changed. Thanks ;)
